# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WXLApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WXLApp
  pod 'SnapKit'
  pod 'Then'
  pod 'Moya'
  pod 'HandyJSON', '~> 4.0.0-beta.1'
  pod 'Kingfisher'
  pod 'Reusable'
  pod 'LLCycleScrollView'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'HMSegmentedControl'
  pod 'IQKeyboardManagerSwift'
  pod 'EmptyDataSet-Swift'
end
